#!/bin/bash
cross_git_repo_path=/home/mbarete/Escritorio/0_PYTHON/Mbarete/
cross_git_repo_branch=master
cross_git_repo_email=mathiaslucasvidipy@gmail.com
cross_git_repo_whatsapp="+595991753962"
cross_sub_proyectos=codigoLibre
cross_temporal=/tmp/temp_mbarete
cross_version=1.0
cross_modo_seguro=false
cross_os_name=posix
cross_file=info.auto.
cross_pwd_practicas=/home/mbarete/Escritorio/0_PYTHON/Mbarete/mbarete/practicas/
cross_pwd_consolas=/home/mbarete/Escritorio/0_PYTHON/Mbarete/mbarete/consolas/
prefijo=cross_
cross_ignorar=.auto.
cross_OS=linux
cross_tmp=/tmp/
cross_OS_VERSION="20.04.4 LTS (Focal Fossa)"
cross_OS_ID=ubuntu
cross_OS_ID_LIKE=debian
cross_OS_PRETTY_NAME="Linux Lite 5.6"
cross_uname_sysname=Linux
cross_uname_nodename=mbarete-HP-15-Notebook-PC
cross_uname_release=5.4.0-104-generic
cross_uname_version="#118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022"
cross_uname_machine=x86_64
cross_V="ubuntu, Linux Lite 5.6"
cross_sys_prefix="/usr"
cross_sys_platform=linux
cross_sys_version="3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]"
cross_git_branch=master
cross_git_repo_username=MbaretePythonPY
cross_git_repo_name=Mbarete.git
cross_git_email=mathiaslucasvidipy@gmail.com
cross_git_username=MbaretePythonPY
cross_fuente=mbarete\consolas\
cross_install=sudo apt install
cross_install_flatpack=sudo flatpack install
